# Generated by Django 2.1 on 2018-08-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoIntegrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_alternativa', models.TextField(max_length=300)),
                ('resposta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(max_length=300)),
                ('qtd_respostas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=150)),
                ('descricao_evento', models.TextField(max_length=300)),
                ('edicao', models.CharField(max_length=5)),
                ('local_evento', models.CharField(max_length=50)),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(verbose_name='Data da Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='PalestranteInstrutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_palestrante_instrutor', models.CharField(max_length=100)),
                ('mini_curriculo', models.TextField(max_length=300)),
                ('foto_palestrante', models.ImageField(upload_to='images')),
                ('tipo', models.CharField(choices=[('palestrante', 'Palestrante'), ('instrutor', 'Instrutor')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PalestraOficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_palestra', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=300)),
                ('data_po', models.DateField(verbose_name='Data')),
                ('hora_po', models.TimeField()),
                ('duracao', models.TimeField()),
                ('tipo', models.CharField(choices=[('palestra', 'Palestra'), ('oficina', 'Oficina')], max_length=10)),
                ('id_evento', models.ForeignKey(on_delete=False, to='projetoIntegrador.Evento')),
                ('id_palestrante_instrutor', models.ForeignKey(on_delete=False, to='projetoIntegrador.PalestranteInstrutor')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado_questao', models.TextField(max_length=300)),
                ('id_avaliacao', models.ForeignKey(on_delete=False, to='projetoIntegrador.Avaliacao')),
            ],
        ),
        migrations.RenameField(
            model_name='sugestoes',
            old_name='sugetaoResposta',
            new_name='sugetao',
        ),
        migrations.RemoveField(
            model_name='sugestoes',
            name='nome',
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_palestra_oficina',
            field=models.ForeignKey(on_delete=False, to='projetoIntegrador.PalestraOficina'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=False, to='projetoIntegrador.Pessoa'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='evento',
            field=models.ForeignKey(on_delete=False, to='projetoIntegrador.Evento'),
        ),
        migrations.AddField(
            model_name='alternativas',
            name='id_questao',
            field=models.ForeignKey(on_delete=False, to='projetoIntegrador.Questoes'),
        ),
        migrations.AddField(
            model_name='sugestoes',
            name='pessoa_sugestoes',
            field=models.ManyToManyField(to='projetoIntegrador.Pessoa'),
        ),
    ]
